# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresadose',
            name='Foto',
            field=models.ImageField(blank=True, upload_to='Egresados_Fotos'),
        ),
    ]
